#!/usr/bin/env python3
"""Regenerate knowledge/map_graph.py from a local pret/pokefirered checkout.

Usage:
    python tools/gen_map_graph.py [path-to-pokefirered] > knowledge/map_graph.py

Reads data/maps/map_groups.json (group order → map index) and each
data/maps/<Map>/map.json (its MAP_* id + edge connections), and emits a
(map_bank, map_id) → {direction: (map_bank, map_id)} graph matching
game/constants and knowledge.navigation.MAP_NAMES. Directions are the edge you
cross to reach the neighbour (up→North, down→South, left→West, right→East).
"""
import json
import os
import sys

DIRW = {"up": "North", "down": "South", "left": "West", "right": "East"}


def build(pf: str) -> dict:
    groups = json.load(open(f"{pf}/data/maps/map_groups.json"))
    order = groups["group_order"]
    const_to_gn = {}
    for gi, gname in enumerate(order):
        if not gname.startswith("gMapGroup_"):
            continue
        for ni, dname in enumerate(groups[gname]):
            mj = f"{pf}/data/maps/{dname}/map.json"
            if os.path.exists(mj):
                const_to_gn[json.load(open(mj))["id"]] = (gi, ni)
    graph = {}
    for gname in order:
        if not gname.startswith("gMapGroup_"):
            continue
        for dname in groups[gname]:
            mj = f"{pf}/data/maps/{dname}/map.json"
            if not os.path.exists(mj):
                continue
            d = json.load(open(mj))
            src = const_to_gn.get(d["id"])
            for c in (d.get("connections") or []):
                dst = const_to_gn.get(c["map"])
                dr = DIRW.get(c["direction"])
                if src and dst and dr:
                    graph.setdefault(src, {})[dr] = dst
    return graph


def main():
    pf = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1 else "~/Projects/pokefirered")
    graph = build(pf)
    out = sys.stdout
    out.write('"""Overworld map connection graph — which map edge leads to which map.\n\n')
    out.write("GENERATED by tools/gen_map_graph.py from the pret/pokefirered decomp map data.\n")
    out.write("Keys/values are (map_bank, map_id) matching game/constants and\n")
    out.write("knowledge.navigation.MAP_NAMES. Direction = the edge you cross to reach the\n")
    out.write("neighbour. These are seamless edge CONNECTIONS only (not building/cave warps),\n")
    out.write("so a route here is map-adjacency; a hop can still be unwalkable if a dungeon\n")
    out.write("blocks the map (e.g. Mt. Moon splits Route 4). go_to executes hop-by-hop and\n")
    out.write('stops if a hop is blocked."""\n')
    out.write("from collections import deque\n\n")
    out.write("MAP_CONNECTIONS: dict[tuple[int, int], dict[str, tuple[int, int]]] = {\n")
    for src in sorted(graph):
        edges = ", ".join(f'"{d}": {graph[src][d]}' for d in sorted(graph[src]))
        out.write(f"    {src}: {{{edges}}},\n")
    out.write("}\n\n\n")
    out.write(
        "def bfs_route(start: tuple[int, int], goal: tuple[int, int])"
        " -> list[tuple[str, tuple[int, int]]] | None:\n"
        '    """Shortest connection route from start to goal as [(direction, next_map), ...],\n'
        '    [] if already there, or None if unreachable via connections."""\n'
        "    if start == goal:\n"
        "        return []\n"
        "    q = deque([(start, [])])\n"
        "    seen = {start}\n"
        "    while q:\n"
        "        cur, path = q.popleft()\n"
        "        for direction, nb in sorted(MAP_CONNECTIONS.get(cur, {}).items()):\n"
        "            if nb == goal:\n"
        "                return path + [(direction, nb)]\n"
        "            if nb not in seen:\n"
        "                seen.add(nb)\n"
        "                q.append((nb, path + [(direction, nb)]))\n"
        "    return None\n"
    )


if __name__ == "__main__":
    main()
